color = "Always"
condense_wildcard_suffixes = true
fn_single_line = true
force_explicit_abi = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_arm_blocks = false
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
